### ISSUE TITLE
Epic: Backend?

### ISSUE THREAD

**Issue by nelsonic** [RobStallion/chess-elm#18]
# Story (Epic)

**As a person** that plays IRL chess and wants to play **_remote_ chess** 
**I need** a way of ***saving*** the **moves** made in the game,
**so that** my remote partner/opponent can see them and make their next move!

> I know this is on your **_mental_ list**, but it's something someone **`else`** might be able to _help_ with,
> so capturing it in an issue means the requirement(s) can be discussed and progress made ... 😉 

# Proposed Schema (_MVP_)

+ [ ] players
  + [ ] id: int (PK)
  + [ ] inserted_at: timestamp
  + [ ] email: binary (encrypted)
  + [ ] email_hash: binary (_for fast lookup when logging in_)
  + [ ] password: binary (hash) (_e.g:_ https://github.com/dwyl/fields/blob/master/lib/password.ex)
+ [ ] sessions (_for authentication ... could just use https://github.com/dwyl/auth if it was ready ...?_  🤔) 
  + [ ] id: binary (CID?)
  + [ ] inserted_at:  timestamp
  + [ ] browser_hash: string (see [github.com/dwyl/hits-elixir > `get_user_agent_string`](https://github.com/dwyl/hits-elixir/blob/b2ed9c10aabc20a36f24c185a5f2a9831b1652d3/lib/hits.ex#L45))
  + [ ] player_id: int (FK)

+ [ ] games
  + [ ] id: int (PK)
  + [ ] inserted_at: timestamp
  + [ ] white: int (player_id FK)
  + [ ] black (player_id)

+ [ ] moves
  + [ ] id: int (PK)
  + [ ] inserted_at: timestamp
  + [ ] game_id: int (FK)
  + [ ] move: string
  > Would you store _just_ the "move" e.g: "**Bb5**" or the _complete_ board on each move (FEN) ?

+ [ ] ***Authentication*** using:
  + [ ] Email & Password - the most basic auth possible just to have game ownership.

# Open Questions

+ Attempt to build your _own_ backed from scratch as a learning exercise or use [python-chess](https://github.com/niklasf/python-chess) ?
+ Is the objective to allow _human_ players to play remotely (_i.e. we only need to record moves so they can be stored, transmitted and displayed in the interface_) ***OR*** is the objective to be able to parse the available game datasets in order to **_suggest_** the **_statistically strongest_ move**  #10 ? e.g:
  + https://www.kaggle.com/datasnaek/chess
  + https://database.chessbase.com
  + https://www.ficsgames.org
+ Anything _else_ required before the MVP backend can be _started_?

Example of game using Algebraic Notation: 
https://www.chess.com/article/view/magnus-carlsen-s-biggest-secret

![image](https://user-images.githubusercontent.com/194400/54147840-f4ed0500-442a-11e9-915a-5469250f7473.png)

# References

In _drafting_ a (_suggested_) schema to store _moves_ in a game, I consulted the following SO Q/A:
+ https://stackoverflow.com/questions/21374846/efficient-storage-of-a-chess-position
+ https://chess.stackexchange.com/questions/6061/do-grandmasters-think-using-algebraic-notation
+ https://chess.stackexchange.com/questions/8500/alternatives-to-the-fen-notation
+ Video intro to Algebraic Notation: https://youtu.be/5_uEUwfKUhc + https://youtu.be/ijTPtWihsXw
+ Algebraic Notation: https://en.wikipedia.org/wiki/Algebraic_notation_(chess) (_most common_)
+ Forsyth–Edwards Notation (FEN): https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation (_complete state of board_)
+ Descriptive Notation: https://en.wikipedia.org/wiki/Descriptive_notation (_descriptive... less common_)
+ https://towardsdatascience.com/predicting-professional-players-chess-moves-with-deep-learning-9de6e305109e 
+ https://github.com/niklasf/python-chess _lots_ of insight in here.
+ Encyclopedia of Chess Openings (ECO): https://github.com/niklasf/eco/blob/master/eco.json

**Comment by nelsonic** [comment]
[![HitCount](http://hits.dwyl.io/robstallion/chess-elm.svg)](http://hits.dwyl.io/robstallion/chess-elm)
